### ISSUE TITLE
Show sign up/attendee list

### ISSUE THREAD

**Issue by stuartphilp** [groovecoder/mozlando-beers-and-ears#7]

**Comment by stuartphilp** [comment]
in the list you could maybe link to people's profile, or have a button to quickly add as a friend (then we can use the untappd app during orlando to see what people are doing)

**Comment by groovecoder** [comment]
Version 1 will be the profile link and people can add from there.

Version 2 will use the Untappd API to add them as friends.

**Comment by stuartphilp** [comment]
@groovecoder nice work!
